### PR TITLE
Occupancy status, plus nits

### LINKED ISSUE #34: Occupancy Status
~We should first wait for the current efforts around improving this functionality at the GTFS spec level to come to rest, and then implement whatever is defined there after it exits the experimental stage.~

* Proposal: Support multi-car crowding in GTFS-RT - https://github.com/google/transit/pull/237
* Proposal: GTFS-MeanOccupancies - https://github.com/google/transit/pull/240

This is ready to go. Needs a design, but otherwise can be worked on.

Output for `api/where/arrivals-and-departures-for-stop/1_8407.json`: 

[1_8407.json.zip](https://github.com/OneBusAway/OBAKit/files/5797653/1_8407.json.zip)

Validation can be done on WMATA's servers.

Corresponding Android issue: https://github.com/OneBusAway/onebusaway-android/issues/1059

### PR DESCRIPTION
**Pull request by aaronbrethorst**
Resolves #34

### CODE REVIEW

**Comment by barbeau** [comment]
Just curious - could you share a screenshot of the final UI design?

**Comment by aaronbrethorst** [comment]
@barbeau attached!

Simulator Screen Shot - iPhone 12 Pro - 2021-07-12 at 16 20 50

Screen Shot 2021-07-12 at 4 21 09 PM

**Comment by barbeau** [comment]
Nice! I think I prefer this to the multicolor (red/green) to denote realtime we currently have on Android. That was really intended to be a placeholder for further testing. I may change to the same.

**Comment by aaronbrethorst** [comment]
Right on! let me know if I can help! :)

**Comment by ualch9** [comment]
FYI, iOS 15 has `person.3.sequence` that could be used to compact the view down.
image

**Comment by aaronbrethorst** [comment]
@ualch9 good catch! That'll make a great addition

**Pull request merged**
