### PR TITLE
OBAKitCore Identifiable

### PR DESCRIPTION
**Pull request by ualch9**
Somewhat related to #292 

I’m playing around with DiffableTableView / DiffableCollectionView right now, so i figured i’ll put this here for now. I tried diffable table view and it’s pretty straightforward, but I’ll probably use UI collection view for everything when i’m done.

### CODE REVIEW

**Comment by aaronbrethorst** [comment]
Cool, I'm excited to see you forging ahead on this! I was hoping we'd be able to get off of IGListKit once iOS 13 was the baseline.

**Comment by ualch9** [comment]
I got kinda of carried away with this, so I want to separate IGListKit → UICollectionView and #292.

@aaronbrethorst I think I got most models, lmk if there are any more in obakitcore that should conform to identifiable.

**Review by aaronbrethorst — CHANGES_REQUESTED** [review]
In general, nice work!

I don't think the the built-in `UITableViewCell`s are going to be sufficient for our needs on this controller, at least not without some munging of the data that is rendered in the subtitle, or constraining the height of the cells.

image

**Comment by ualch9** [comment]
@aaronbrethorst Oops, I didn't mean to include that, just Identifiable for this PR. Updated history.

**Review by aaronbrethorst — APPROVED** [review]
lgtm! 👍 I'll merge as soon as CI finishes.

**Pull request merged**
