### PR TITLE
Migrate qualifying dependencies to SwiftPM

### PR DESCRIPTION
**Pull request by ualch9**
Dependencies still on Carthage:
- IGListKit https://github.com/Instagram/IGListKit/issues/1368
- BulletinBoard https://github.com/alexaubry/BulletinBoard/issues/158
- OneSignal https://github.com/OneSignal/OneSignal-iOS-SDK/issues/179

### CODE REVIEW

**Comment by aaronbrethorst** [comment]
Great progress! Here are a few things I'd like to see included:

The package resolution data needs to be checked in, which will require modifying `.gitignore`.

```
## SwiftPM
OBAKit.xcodeproj/**
!OBAKit.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
``` 

SwiftProtobuf should be pinned at `minorVersion` and the other packages should be pinned at `exactVersion` — I don't trust most package authors to follow semver and I don't want to deal with unexpected bad breaks :)

**Comment by aaronbrethorst** [comment]
@ualch9 what is necessary to promote this from a draft to a ready-for-merge PR? Anything I can do to help?

**Comment by ualch9** [comment]
Should be OK now, waiting on CI.

**Comment by ualch9** [comment]
@aaronbrethorst I'm having trouble checking in the Package.resolved file, please take a look.

**Comment by aaronbrethorst** [comment]
This has been split apart and merged as three separate PRs.

**Pull request closed without merging**
