### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by aaronbrethorst**

### CODE REVIEW

**Comment by ualch9** [comment]
Why remove the progress view? It was working fine with me.

**Comment by aaronbrethorst** [comment]
@ualch9 

> Why remove the progress view? It was working fine with me.

What's your environment? iOS 14? Here's what I'm seeing with Xcode 11.5/iOS 13:

```
Test Case '-[OBAKitTests.RegionsModelOperationTests testSuccessfulRequest]' started.
2020-07-12 15:49:31.024291-0700 App[56881:11728402] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSURLSessionDataTask progress]: unrecognized selector sent to instance 0x600003361fe0'
```

**Comment by ualch9** [comment]
@aaronbrethorst 
> 
> > Why remove the progress view? It was working fine with me.
> 
> What's your environment? iOS 14? Here's what I'm seeing with Xcode 11.5/iOS 13:
> 
> ```
> Test Case '-[OBAKitTests.RegionsModelOperationTests testSuccessfulRequest]' started.
> 2020-07-12 15:49:31.024291-0700 App[56881:11728402] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSURLSessionDataTask progress]: unrecognized selector sent to instance 0x600003361fe0'
> ```

Same testing environment. Behavior works in-app.
This issue occurs when we provide a mock session, which is why this exception only throws when xctesting ([stackoverflow](https://stackoverflow.com/questions/56419151/mocking-urlsession-for-api-testing-is-giving-unrecognized-selector-sent-to-insta))

The fix below fixes the issue, but I am not familiar with the testing suite so I'll leave it up to you in regards to implementing the fix.

## Fix (as git patch)
This is also attached: [fix-nil-progress-xctest.patch.zip](https://github.com/OneBusAway/OBAKit/files/4910091/fix-nil-progress-xctest.patch.zip).
```git
diff --git a/OBAKitTests/Helpers/Mocks/MockDataLoader.swift b/OBAKitTests/Helpers/Mocks/MockDataLoader.swift
index abf1a3fb..4b0483b3 100644
--- a/OBAKitTests/Helpers/Mocks/MockDataLoader.swift
+++ b/OBAKitTests/Helpers/Mocks/MockDataLoader.swift
@@ -17,6 +17,12 @@ struct MockDataResponse {
     let matcher: MockDataLoaderMatcher
 }
 
+class MockTask: URLSessionDataTask {
+    override var progress: Progress {
+        return Progress()
+    }
+}
+
 class MockDataLoader: NSObject, URLDataLoader {
     var mockResponses = [MockDataResponse]()
 
@@ -34,7 +40,7 @@ class MockDataLoader: NSObject, URLDataLoader {
 
         completionHandler(response.data, response.urlResponse, response.error)
 
-        return URLSessionDataTask()
+        return MockTask()
     }
 
     // MARK: - Response Mapping

```

**Comment by aaronbrethorst** [comment]
@ualch9 oooooh, I see. thank you for the clarification and the patch. I've added the latter to the codebase.

**Pull request merged**
