### PR TITLE
Change minimum supported version to iOS 13.7

### PR DESCRIPTION
**Pull request by aaronbrethorst**
I had a change of heart on supporting iOS 12. This is for two primary reasons:

1. I want to be able to use XCFrameworks (consume and publish).
2. I want to set us up to move off of IGListKit and onto the built-in diffable data sources feature at some point.

Furthermore, per Apple, 92% of devices released in the last four years are running iOS 13. https://developer.apple.com/support/app-store/

Thoughts, @ualch9?

### CODE REVIEW

**Comment by ualch9** [comment]
13.7 seems aggressive, how many users are currently on 13.7 for old oba?

**Comment by aaronbrethorst** [comment]
@ualch9 Fair. I'd be willing to go down to 13.6, but I expect that it can be bumped up by the time this app ships.

image

**Comment by aaronbrethorst** [comment]
OK, I updated the minimum version to iOS 13.6. LMK if you have any reservations, @ualch9

**Comment by ualch9** [comment]
👀 👍

**Pull request merged**
